"""
Taste ranking model for the Love your Playlist model.

rank(profile, candidate_tracks, n, lyric_weight, audio_weight, diversity_penalty) -> list[dict]

Ranks candidate tracks by similarity to the user's taste profile,
combining semantic lyric similarity and audio feature proximity,
while applying a diversity penalty to ensure genre/artist variety.
"""

from __future__ import annotations

from typing import Any

import numpy as np


def _cosine_similarity(v1: np.ndarray, v2: np.ndarray) -> float:
    """Computes cosine similarity between two 1D vectors."""
    n1 = np.linalg.norm(v1)
    n2 = np.linalg.norm(v2)
    if n1 == 0 or n2 == 0:
        return 0.0
    return float(np.dot(v1, v2) / (n1 * n2))


def _audio_similarity(
    profile_mean: np.ndarray,
    track_audio: np.ndarray,
    profile_std: np.ndarray | None = None,
) -> float:
    """Computes audio similarity score in [0, 1]."""
    if profile_std is not None and np.all(profile_std > 0):
        diff = (profile_mean - track_audio) / (profile_std + 1e-4)
    else:
        diff = profile_mean - track_audio

    dist = float(np.linalg.norm(diff))
    sim = float(np.exp(-dist / 3.0))
    return max(0.0, min(1.0, sim))


def rank(
    profile: dict[str, Any],
    candidate_tracks: list[dict[str, Any]],
    n: int = 25,
    *,
    lyric_weight: float = 0.5,
    audio_weight: float = 0.5,
    diversity_penalty: float = 0.2,
    max_tracks_per_artist: int = 3,
) -> list[dict[str, Any]]:
    """
    Ranks candidate tracks against the taste profile.

    Parameters:
        profile: dict generated by build_profile()
        candidate_tracks: list of track dicts in the shared track format
        n: number of top tracks to return
        lyric_weight: float in [0.0, 1.0], weight given to lyric semantic match
        audio_weight: float in [0.0, 1.0], weight given to audio feature match
        diversity_penalty: float in [0.0, 1.0], penalty applied to repeated artists/genres
        max_tracks_per_artist: maximum number of tracks from the same artist in the output

    Returns:
        List of the top n ranked track dicts, each augmented with:
            - 'score': float (overall similarity score 0.0 to 1.0)
            - 'lyric_similarity': float (0.0 to 1.0)
            - 'audio_similarity': float (0.0 to 1.0)
            - 'match_reason': str (human-readable explanation)
    """
    if not candidate_tracks:
        return []

    # Normalize weights
    total_w = lyric_weight + audio_weight
    if total_w > 0:
        norm_lyric_w = lyric_weight / total_w
        norm_audio_w = audio_weight / total_w
    else:
        norm_lyric_w = 0.5
        norm_audio_w = 0.5

    profile_lyric = profile.get("lyric_embedding")
    profile_audio_mean = profile.get("audio_features_mean")
    profile_audio_std = profile.get("audio_features_std")

    scored_candidates: list[dict[str, Any]] = []

    for track in candidate_tracks:
        track_lyric = track.get("lyric_embedding")
        track_audio = track.get("audio_features_normalized")

        # 1. Lyric similarity
        if (
            profile_lyric is not None
            and track_lyric is not None
            and isinstance(track_lyric, (np.ndarray, list))
            and len(track_lyric) > 0
        ):
            lyric_sim = _cosine_similarity(profile_lyric, np.asarray(track_lyric))
            lyric_sim = max(0.0, (lyric_sim + 1.0) / 2.0)
            has_lyric_match = True
        else:
            lyric_sim = 0.5
            has_lyric_match = False

        # 2. Audio similarity
        if (
            profile_audio_mean is not None
            and track_audio is not None
            and isinstance(track_audio, (np.ndarray, list))
            and len(track_audio) > 0
        ):
            audio_sim = _audio_similarity(
                profile_audio_mean, np.asarray(track_audio), profile_audio_std
            )
        else:
            audio_sim = 0.5

        # 3. Combined Base Score
        if has_lyric_match:
            base_score = (norm_lyric_w * lyric_sim) + (norm_audio_w * audio_sim)
        else:
            base_score = (0.2 * lyric_sim) + (0.8 * audio_sim)

        # Human-readable match explanation
        reasons = []
        if has_lyric_match and lyric_sim > 0.70:
            reasons.append(f"Strong lyric theme match ({lyric_sim:.0%})")
        elif has_lyric_match and lyric_sim > 0.55:
            reasons.append(f"Matching lyric vibe ({lyric_sim:.0%})")

        if audio_sim > 0.75:
            reasons.append(f"Great audio vibe match ({audio_sim:.0%})")
        elif audio_sim > 0.60:
            reasons.append(f"Fits audio rhythm ({audio_sim:.0%})")

        reason_str = " & ".join(reasons) if reasons else "Good overall taste match"

        track_copy = dict(track)
        track_copy["score"] = float(base_score)
        track_copy["lyric_similarity"] = float(lyric_sim)
        track_copy["audio_similarity"] = float(audio_sim)
        track_copy["match_reason"] = reason_str
        scored_candidates.append(track_copy)

    # 4. Diversity Selection
    scored_candidates.sort(key=lambda t: t["score"], reverse=True)

    selected: list[dict[str, Any]] = []
    artist_counts: dict[str, int] = {}
    pool = list(scored_candidates)

    while pool and len(selected) < n:
        best_idx = 0
        best_adjusted_score = -1e9

        for i, cand in enumerate(pool):
            art = str(cand.get("artist", "")).strip().lower()
            current_count = artist_counts.get(art, 0)

            if current_count >= max_tracks_per_artist:
                continue

            penalty = diversity_penalty * current_count
            adjusted_score = cand["score"] - penalty

            if adjusted_score > best_adjusted_score:
                best_adjusted_score = adjusted_score
                best_idx = i

        if best_adjusted_score == -1e9:
            best_idx = 0

        chosen = pool.pop(best_idx)
        art = str(chosen.get("artist", "")).strip().lower()
        artist_counts[art] = artist_counts.get(art, 0) + 1
        selected.append(chosen)

    return selected
